# file: tasks/main.yml
---
- name: Install NFS kernel server
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"

- name: Install NFS utils
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Create NFS share directory
  ansible.builtin.file:
    path: /nfs
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777

- name: Configure NFS exports
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: Restart NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
