---
- name: Install NFS kernel server
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present
  when: ansible_os_family == "Debian"

- name: Install NFS utils
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Create NFS directory
  ansible.builtin.file:
    path: "{{ nfs_share }}"
    state: directory
    owner: "{{ nfs_owner }}"
    group: "{{ nfs_group }}"
    mode: "{{ nfs_mode }}"

- name: Configure NFS exports
  blockinfile:
    path: /etc/exports
    create: true
    block: |
      {{ nfs_share }} {{ nfs_client }}({{ nfs_options }})
  notify:
    - Export NFS shares
    - Restart NFS server
