---
- name: Export NFS shares
  ansible.builtin.shell: exportfs -a
  become: true

- name: Restart NFS server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
  become: true
